//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicoV2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicoV2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -viewCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01001 {
            get {
                return ResourceManager.GetString("VM01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +viewCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01002 {
            get {
                return ResourceManager.GetString("VM01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -mylistCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01003 {
            get {
                return ResourceManager.GetString("VM01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +mylistCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01004 {
            get {
                return ResourceManager.GetString("VM01004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -commentCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01005 {
            get {
                return ResourceManager.GetString("VM01005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +commentCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01006 {
            get {
                return ResourceManager.GetString("VM01006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -startTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01007 {
            get {
                return ResourceManager.GetString("VM01007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +startTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01008 {
            get {
                return ResourceManager.GetString("VM01008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -lastCommentTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01009 {
            get {
                return ResourceManager.GetString("VM01009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +lastCommentTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01010 {
            get {
                return ResourceManager.GetString("VM01010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -lengthSeconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01011 {
            get {
                return ResourceManager.GetString("VM01011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +lengthSeconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01012 {
            get {
                return ResourceManager.GetString("VM01012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -Regist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01013 {
            get {
                return ResourceManager.GetString("VM01013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +Regist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01014 {
            get {
                return ResourceManager.GetString("VM01014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -MylistComment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01015 {
            get {
                return ResourceManager.GetString("VM01015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +MylistComment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01016 {
            get {
                return ResourceManager.GetString("VM01016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01017 {
            get {
                return ResourceManager.GetString("VM01017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01018 {
            get {
                return ResourceManager.GetString("VM01018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -StartTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01019 {
            get {
                return ResourceManager.GetString("VM01019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +StartTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01020 {
            get {
                return ResourceManager.GetString("VM01020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -viewCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01021 {
            get {
                return ResourceManager.GetString("VM01021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +viewCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01022 {
            get {
                return ResourceManager.GetString("VM01022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01023 {
            get {
                return ResourceManager.GetString("VM01023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01024 {
            get {
                return ResourceManager.GetString("VM01024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -commentCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01025 {
            get {
                return ResourceManager.GetString("VM01025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +commentCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01026 {
            get {
                return ResourceManager.GetString("VM01026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -mylistCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01027 {
            get {
                return ResourceManager.GetString("VM01027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +mylistCounter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01028 {
            get {
                return ResourceManager.GetString("VM01028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -lengthSeconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01029 {
            get {
                return ResourceManager.GetString("VM01029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +lengthSeconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01030 {
            get {
                return ResourceManager.GetString("VM01030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01031 {
            get {
                return ResourceManager.GetString("VM01031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01032 {
            get {
                return ResourceManager.GetString("VM01032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01033 {
            get {
                return ResourceManager.GetString("VM01033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01034 {
            get {
                return ResourceManager.GetString("VM01034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   music に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01035 {
            get {
                return ResourceManager.GetString("VM01035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01036 {
            get {
                return ResourceManager.GetString("VM01036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   anime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01037 {
            get {
                return ResourceManager.GetString("VM01037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01038 {
            get {
                return ResourceManager.GetString("VM01038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   animal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01039 {
            get {
                return ResourceManager.GetString("VM01039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   que に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01040 {
            get {
                return ResourceManager.GetString("VM01040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   radio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01041 {
            get {
                return ResourceManager.GetString("VM01041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sport に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01042 {
            get {
                return ResourceManager.GetString("VM01042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   politics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01043 {
            get {
                return ResourceManager.GetString("VM01043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01044 {
            get {
                return ResourceManager.GetString("VM01044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   science に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01045 {
            get {
                return ResourceManager.GetString("VM01045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01046 {
            get {
                return ResourceManager.GetString("VM01046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cooking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01047 {
            get {
                return ResourceManager.GetString("VM01047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01048 {
            get {
                return ResourceManager.GetString("VM01048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   diary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01049 {
            get {
                return ResourceManager.GetString("VM01049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01050 {
            get {
                return ResourceManager.GetString("VM01050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01051 {
            get {
                return ResourceManager.GetString("VM01051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01052 {
            get {
                return ResourceManager.GetString("VM01052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lecture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01053 {
            get {
                return ResourceManager.GetString("VM01053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01054 {
            get {
                return ResourceManager.GetString("VM01054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01055 {
            get {
                return ResourceManager.GetString("VM01055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01056 {
            get {
                return ResourceManager.GetString("VM01056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   r18 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01057 {
            get {
                return ResourceManager.GetString("VM01057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hourly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01058 {
            get {
                return ResourceManager.GetString("VM01058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01059 {
            get {
                return ResourceManager.GetString("VM01059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01060 {
            get {
                return ResourceManager.GetString("VM01060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01061 {
            get {
                return ResourceManager.GetString("VM01061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   total に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01062 {
            get {
                return ResourceManager.GetString("VM01062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VM01063 {
            get {
                return ResourceManager.GetString("VM01063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW01001 {
            get {
                return ResourceManager.GetString("VW01001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW01002 {
            get {
                return ResourceManager.GetString("VW01002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW01003 {
            get {
                return ResourceManager.GetString("VW01003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW01004 {
            get {
                return ResourceManager.GetString("VW01004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02001 {
            get {
                return ResourceManager.GetString("VW02001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワード検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02002 {
            get {
                return ResourceManager.GetString("VW02002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02003 {
            get {
                return ResourceManager.GetString("VW02003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02004 {
            get {
                return ResourceManager.GetString("VW02004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02005 {
            get {
                return ResourceManager.GetString("VW02005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02006 {
            get {
                return ResourceManager.GetString("VW02006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02007 {
            get {
                return ResourceManager.GetString("VW02007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02008 {
            get {
                return ResourceManager.GetString("VW02008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02009 {
            get {
                return ResourceManager.GetString("VW02009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastCommentTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02010 {
            get {
                return ResourceManager.GetString("VW02010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02011 {
            get {
                return ResourceManager.GetString("VW02011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW02012 {
            get {
                return ResourceManager.GetString("VW02012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03001 {
            get {
                return ResourceManager.GetString("VW03001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03002 {
            get {
                return ResourceManager.GetString("VW03002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03003 {
            get {
                return ResourceManager.GetString("VW03003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03004 {
            get {
                return ResourceManager.GetString("VW03004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03005 {
            get {
                return ResourceManager.GetString("VW03005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03006 {
            get {
                return ResourceManager.GetString("VW03006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03007 {
            get {
                return ResourceManager.GetString("VW03007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03008 {
            get {
                return ResourceManager.GetString("VW03008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03009 {
            get {
                return ResourceManager.GetString("VW03009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03010 {
            get {
                return ResourceManager.GetString("VW03010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03011 {
            get {
                return ResourceManager.GetString("VW03011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW03012 {
            get {
                return ResourceManager.GetString("VW03012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04001 {
            get {
                return ResourceManager.GetString("VW04001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04002 {
            get {
                return ResourceManager.GetString("VW04002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04003 {
            get {
                return ResourceManager.GetString("VW04003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04004 {
            get {
                return ResourceManager.GetString("VW04004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04005 {
            get {
                return ResourceManager.GetString("VW04005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04006 {
            get {
                return ResourceManager.GetString("VW04006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04007 {
            get {
                return ResourceManager.GetString("VW04007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04008 {
            get {
                return ResourceManager.GetString("VW04008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VW04009 {
            get {
                return ResourceManager.GetString("VW04009", resourceCulture);
            }
        }
    }
}
